### ISSUE TITLE
All event handler on wrapper must use stopPropagation()

### ISSUE THREAD

**Issue by japhendywijaya2** [jamessimone/lwc-modal#6]
First of all, your solution is very much helpful. i've spent 3 days and still have no idea how to create a modal component that's conforming with LDS guidelines. So thankyou very much for sharing your solution 

And i'm quite new to LWC and html, so please excuse me if my understanding is wrong.
Is it correct that using your solution, all event handler of the Wrapper component for the modal must use `event.stopPropagation();`  or else they will trigger the click listener inside the modal component hence toggling isOpen property ?

How about if the isOpen state is placed on the wrapper instead, so that the Modal component just need to dispatch event, this way all wrapper event Handler won't need to configure `event.stopPropagation();`

**Comment by jamessimone** [comment]
@japhendywijaya2 thanks for stopping by. Modal wrapper, as a component, is meant to simply be an example of using the modal component; this repo is more of an LWC recipe and is not meant to be the end-all definitive word on how to create modals. Indeed, modal progress in LWC has come a long way (between the quick action panel, LightningConfirm/LightningAlert dialogs, etc …) in the time since this repo was made.

My advice would be to do what works for you! If that means it’s easier to actually use the modal wrapper as a place to store open/closed state — by all means, do so! I would probably rename the two components, in my own projects, if I were to do that to reflect the fact that the “wrapper” was now really part of the implementation. Your mileage may vary.

I’m going to close this for now but feel free to continue the discussion!
